### ISSUE TITLE
How do I run your model using a road network in `networkx.Graph()` format (downloaded using osmnx)?

### ISSUE THREAD

**Issue by csjiezhao** [changyanchuan/SARN#2]
I noticed that your code includes a lot of preprocessing in the osm2roadnetwork file, how can I perform this processing directly on 'networkx.Graph()' and obtain the custom OSMLoader class?

**Comment by changyanchuan** [comment]
We do not have any functions to convert OSMLoader objects to networkx.Graph()s so far. Sorry for inconvenience
